// Code generated by cmd/pressluft-contractgen; DO NOT EDIT.
import type {
  CallbackURLMode,
  JobKind,
  JobStatus,
  NodeStatus,
  ServerStatus,
  SetupState,
  SupportLevel,
} from '~/lib/platform-contract.generated'

export type Capability = "manage_providers" | "manage_servers" | "manage_sites" | "queue_jobs" | "read_activity"
export type Role = 'admin'

export interface Activity {
  id: string
  event_type: string
  category: string
  level: string
  resource_type?: string
  resource_id?: string
  parent_resource_type?: string
  parent_resource_id?: string
  actor_type: string
  actor_id?: string
  title: string
  message?: string
  payload?: string
  requires_attention: boolean
  read_at?: string
  created_at: string
}

export interface ActivityListResponse {
  data: Activity[]
  next_cursor?: string
}

export interface AgentInfo {
  connected: boolean
  status: NodeStatus
  last_seen?: string
  version?: string
  cpu_percent?: number
  mem_used_mb?: number
  mem_total_mb?: number
}

export type AgentStatusMapResponse = AgentStatusMapResponse

export interface AuthActor {
  id: string
  type: string
  email: string
  role: Role
  capabilities?: Capability[]
  authenticated: boolean
  auth_source?: string
}

export interface CreateDomainRequest {
  hostname: string
  kind?: string
  ownership?: string
  status?: string
  site_id?: string
  parent_domain_id?: string
  is_primary?: boolean
}

export interface CreateJobRequest {
  kind: string
  server_id?: string
  payload: unknown
}

export interface CreateProviderRequest {
  type: string
  name: string
  api_token: string
}

export interface CreateProviderResponse {
  id: string
  validation: ValidationResult
}

export interface CreateServerRequest {
  provider_id: string
  name: string
  location: string
  server_type: string
  profile_key: string
}

export interface CreateServerResponse {
  server_id: string
  job_id: string
  status: ServerStatus
}

export interface CreateSiteRequest {
  server_id: string
  name: string
  primary_domain?: string
  primary_domain_config?: { mode: string; hostname?: string; label?: string; parent_domain_id?: string }
  status?: string
  wordpress_path?: string
  php_version?: string
  wordpress_version?: string
}

export interface DeleteDomainResponse {
  domain_id: string
  deleted: boolean
  description: string
}

export interface DeleteServerResponse {
  server_id: string
  job_id: string
  status: ServerStatus
  job_status: JobStatus
  async: boolean
  description: string
}

export interface DeleteSiteResponse {
  site_id: string
  deleted: boolean
  description: string
}

export interface FirewallsResponse {
  server_id: string
  firewalls: { id: number; name: string }[]
}

export interface HealthResponse {
  status: string
  callback_url_mode?: CallbackURLMode
  callback_url_warning?: string
}

export interface Job {
  id: string
  server_id?: string
  kind: string
  status: JobStatus
  current_step: string
  retry_count: number
  last_error?: string
  payload?: string
  started_at?: string
  finished_at?: string
  timeout_at?: string
  created_at: string
  updated_at: string
  command_id?: string
}

export interface JobEvent {
  id: string
  job_id: string
  seq: number
  event_type: string
  level: string
  step_key?: string
  status?: string
  message: string
  payload?: string
  occurred_at: string
}

export interface LoginRequest {
  email: string
  password: string
}

export interface ProviderType {
  type: string
  name: string
  docs_url: string
  abbreviation: string
  description: string
}

export interface RebuildOptionsResponse {
  server_id: string
  server_type: string
  architecture: string
  images: { id: number; name: string; type: string; architecture: string; deprecated: boolean; status: string }[]
}

export interface ResizeOptionsResponse {
  server_id: string
  location: string
  server_type: string
  architecture: string
  server_types: ServerTypeOption[]
}

export interface ServerCatalog {
  locations: ServerLocation[]
  server_types: ServerTypeOption[]
}

export interface ServerCatalogResponse {
  catalog: ServerCatalog
  profiles: ServerProfile[]
}

export interface ServerLocation {
  name: string
  description: string
  country?: string
  city?: string
  network_zone?: string
}

export interface ServerProfile {
  key: string
  name: string
  description: string
  image: string
  artifact_path: string
  support_level: SupportLevel
  configure_guarantee: string
  support_reason?: string
}

export interface ServerTypeOption {
  name: string
  description: string
  cores: number
  memory_gb: number
  disk_gb: number
  architecture: string
  available_at: string[]
  prices: ServerTypePrice[]
}

export interface ServerTypePrice {
  location_name: string
  hourly_gross: string
  monthly_gross: string
  currency: string
}

export interface Service {
  name: string
  description: string
  active_state: string
  load_state: string
}

export interface ServicesResponse {
  server_id: string
  agent_connected: boolean
  services: Service[]
}

export interface StatusResponse {
  status: string
}

export interface StoredDomain {
  id: string
  hostname: string
  kind: string
  ownership: string
  status: string
  site_id?: string
  site_name?: string
  parent_domain_id?: string
  parent_hostname?: string
  is_primary: boolean
  created_at: string
  updated_at: string
}

export interface StoredProvider {
  id: string
  type: string
  name: string
  status: string
  created_at: string
  updated_at: string
}

export interface StoredServer {
  id: string
  provider_id: string
  provider_type: string
  provider_server_id?: string
  ipv4?: string
  ipv6?: string
  name: string
  location: string
  server_type: string
  image: string
  profile_key: string
  status: ServerStatus
  setup_state: SetupState
  setup_last_error?: string
  action_id?: string
  action_status?: string
  has_key: boolean
  node_status?: NodeStatus
  node_last_seen?: string
  node_version?: string
  created_at: string
  updated_at: string
}

export interface StoredSite {
  id: string
  server_id: string
  server_name: string
  name: string
  primary_domain?: string
  status: string
  wordpress_path?: string
  php_version?: string
  wordpress_version?: string
  created_at: string
  updated_at: string
}

export interface UnreadCountResponse {
  count: number
}

export interface UpdateDomainRequest {
  hostname?: string
  kind?: string
  ownership?: string
  status?: string
  site_id?: string
  parent_domain_id?: string
  is_primary?: boolean
}

export interface UpdateSiteRequest {
  server_id?: string
  name?: string
  primary_domain?: string
  status?: string
  wordpress_path?: string
  php_version?: string
  wordpress_version?: string
}

export interface ValidateProviderRequest {
  type: string
  api_token: string
}

export interface ValidationResult {
  valid: boolean
  read_write: boolean
  message: string
  project_name?: string
}

export interface VolumesResponse {
  server_id: string
  volumes: { id: number; name: string; size_gb: number; location: string; status: string; server_id?: number }[]
}

