// Code generated by cmd/pressluft-contractgen; DO NOT EDIT.
export const platformContract = {
  "execution_modes": [
    "dev",
    "single-node-local-control-plane",
    "production-bootstrap"
  ],
  "support_levels": [
    "supported",
    "experimental",
    "unavailable"
  ],
  "server_statuses": [
    "pending",
    "provisioning",
    "configuring",
    "rebuilding",
    "resizing",
    "deleting",
    "deleted",
    "ready",
    "failed"
  ],
  "server_status_groups": {
    "in_progress": [
      "pending",
      "provisioning",
      "configuring",
      "rebuilding",
      "resizing",
      "deleting"
    ],
    "mutation_blocked": [
      "deleting",
      "deleted"
    ],
    "destructive": [
      "rebuilding",
      "resizing",
      "deleting"
    ]
  },
  "setup_states": [
    "not_started",
    "running",
    "degraded",
    "ready"
  ],
  "node_statuses": [
    "online",
    "unhealthy",
    "offline",
    "unknown"
  ],
  "reachable_node_statuses": [
    "online",
    "unhealthy"
  ],
  "node_thresholds": {
    "unhealthy_seconds": 45,
    "offline_seconds": 150
  },
  "callback_url_modes": [
    "unknown",
    "stable",
    "ephemeral"
  ],
  "job_statuses": [
    "queued",
    "running",
    "succeeded",
    "failed"
  ],
  "job_terminal_statuses": [
    "succeeded",
    "failed"
  ],
  "job_kinds": [
    {
      "kind": "configure_server",
      "label": "Server setup",
      "allowed_statuses": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ],
      "destructive": false,
      "experimental": false,
      "execution_path": "worker",
      "dispatch_policy": {
        "queue_server": false
      },
      "timeout_seconds": 1800,
      "retry_limit": 0,
      "recovery": "mark failed on worker interruption; retry setup manually after inspection",
      "steps": [
        {
          "key": "validate",
          "label": "Validating request"
        },
        {
          "key": "configure",
          "label": "Configuring server"
        },
        {
          "key": "finalize",
          "label": "Finalizing"
        }
      ]
    },
    {
      "kind": "delete_server",
      "label": "Server deletion",
      "allowed_statuses": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ],
      "destructive": true,
      "experimental": true,
      "execution_path": "worker",
      "dispatch_policy": {
        "queue_server": true
      },
      "timeout_seconds": 1200,
      "retry_limit": 0,
      "recovery": "mark failed on worker interruption; verify provider-side deletion before retrying manually",
      "queued_server_status": "deleting",
      "steps": [
        {
          "key": "validate",
          "label": "Validating request"
        },
        {
          "key": "delete",
          "label": "Deleting server"
        },
        {
          "key": "finalize",
          "label": "Finalizing"
        }
      ]
    },
    {
      "kind": "deploy_site",
      "label": "Site deployment",
      "allowed_statuses": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ],
      "destructive": false,
      "experimental": false,
      "execution_path": "worker",
      "dispatch_policy": {
        "queue_server": false
      },
      "timeout_seconds": 1500,
      "retry_limit": 0,
      "recovery": "mark failed on worker interruption; inspect site files, database, and routing before retrying manually",
      "steps": [
        {
          "key": "validate",
          "label": "Validating request"
        },
        {
          "key": "deploy",
          "label": "Deploying site"
        },
        {
          "key": "verify",
          "label": "Verifying site routing"
        },
        {
          "key": "finalize",
          "label": "Finalizing"
        }
      ]
    },
    {
      "kind": "manage_volume",
      "label": "Volume management",
      "allowed_statuses": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ],
      "destructive": false,
      "experimental": true,
      "execution_path": "worker",
      "dispatch_policy": {
        "queue_server": true
      },
      "timeout_seconds": 1200,
      "retry_limit": 0,
      "recovery": "mark failed on worker interruption; retry manually after inspection",
      "steps": [
        {
          "key": "validate",
          "label": "Validating request"
        },
        {
          "key": "manage_volume",
          "label": "Managing volume"
        },
        {
          "key": "finalize",
          "label": "Finalizing"
        }
      ]
    },
    {
      "kind": "provision_server",
      "label": "Server infrastructure provisioning",
      "allowed_statuses": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ],
      "destructive": false,
      "experimental": false,
      "execution_path": "worker",
      "dispatch_policy": {
        "queue_server": false
      },
      "timeout_seconds": 1800,
      "retry_limit": 0,
      "recovery": "mark failed on worker interruption; inspect provider state before retrying manually",
      "steps": [
        {
          "key": "validate",
          "label": "Validating request"
        },
        {
          "key": "provision",
          "label": "Provisioning infrastructure"
        }
      ]
    },
    {
      "kind": "rebuild_server",
      "label": "Server rebuild",
      "allowed_statuses": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ],
      "destructive": true,
      "experimental": true,
      "execution_path": "worker",
      "dispatch_policy": {
        "queue_server": true
      },
      "timeout_seconds": 2700,
      "retry_limit": 0,
      "recovery": "mark failed on worker interruption; inspect machine state before retrying manually",
      "queued_server_status": "rebuilding",
      "steps": [
        {
          "key": "validate",
          "label": "Validating request"
        },
        {
          "key": "rebuild",
          "label": "Rebuilding server"
        },
        {
          "key": "finalize",
          "label": "Finalizing"
        }
      ]
    },
    {
      "kind": "resize_server",
      "label": "Server resize",
      "allowed_statuses": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ],
      "destructive": true,
      "experimental": true,
      "execution_path": "worker",
      "dispatch_policy": {
        "queue_server": true
      },
      "timeout_seconds": 1200,
      "retry_limit": 0,
      "recovery": "mark failed on worker interruption; inspect provider-side resize state before retrying manually",
      "queued_server_status": "resizing",
      "steps": [
        {
          "key": "validate",
          "label": "Validating request"
        },
        {
          "key": "resize",
          "label": "Resizing server"
        },
        {
          "key": "finalize",
          "label": "Finalizing"
        }
      ]
    },
    {
      "kind": "restart_service",
      "label": "Service restart",
      "allowed_statuses": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ],
      "destructive": false,
      "experimental": true,
      "execution_path": "agent",
      "dispatch_policy": {
        "queue_server": true
      },
      "timeout_seconds": 120,
      "retry_limit": 0,
      "recovery": "mark failed on worker interruption or timeout; late agent results are ignored",
      "steps": [
        {
          "key": "validate",
          "label": "Validating request"
        },
        {
          "key": "restart_service",
          "label": "Restarting service"
        },
        {
          "key": "finalize",
          "label": "Finalizing"
        }
      ]
    },
    {
      "kind": "update_firewalls",
      "label": "Firewall update",
      "allowed_statuses": [
        "queued",
        "running",
        "succeeded",
        "failed"
      ],
      "destructive": false,
      "experimental": true,
      "execution_path": "worker",
      "dispatch_policy": {
        "queue_server": true
      },
      "timeout_seconds": 900,
      "retry_limit": 0,
      "recovery": "mark failed on worker interruption; retry manually after inspection",
      "steps": [
        {
          "key": "validate",
          "label": "Validating request"
        },
        {
          "key": "update_firewalls",
          "label": "Updating firewalls"
        },
        {
          "key": "finalize",
          "label": "Finalizing"
        }
      ]
    }
  ],
  "config_scopes": {
    "agent": [
      {
        "name": "PRESSLUFT_EXECUTION_MODE",
        "required": false,
        "default_value": "production-bootstrap",
        "description": "Execution mode contract for the agent process."
      }
    ],
    "control-plane": [
      {
        "name": "PRESSLUFT_EXECUTION_MODE",
        "required": false,
        "default_value": "single-node-local-control-plane",
        "description": "Execution mode contract for the control plane."
      },
      {
        "name": "PRESSLUFT_CONTROL_PLANE_URL",
        "required": false,
        "description": "Public base URL used for agent bootstrap and reconnect."
      },
      {
        "name": "PRESSLUFT_TLS_CERT_FILE",
        "required": true,
        "description": "HTTPS certificate file in production-bootstrap mode."
      },
      {
        "name": "PRESSLUFT_TLS_KEY_FILE",
        "required": true,
        "description": "HTTPS private key file in production-bootstrap mode."
      },
      {
        "name": "PRESSLUFT_DB",
        "required": false,
        "description": "SQLite database path."
      },
      {
        "name": "PORT",
        "required": false,
        "default_value": "8080",
        "description": "HTTP listen port."
      },
      {
        "name": "XDG_DATA_HOME",
        "required": false,
        "description": "Base data directory for derived paths."
      },
      {
        "name": "PRESSLUFT_CA_KEY_PATH",
        "required": false,
        "description": "Encrypted CA private key path."
      },
      {
        "name": "PRESSLUFT_AGE_KEY_PATH",
        "required": false,
        "description": "age identity path used for local secret encryption."
      },
      {
        "name": "PRESSLUFT_SESSION_KEY_PATH",
        "required": false,
        "description": "Session HMAC secret path."
      },
      {
        "name": "PRESSLUFT_SESSION_IDLE_TIMEOUT",
        "required": false,
        "default_value": "12h0m0s",
        "description": "Operator session idle timeout."
      },
      {
        "name": "PRESSLUFT_SESSION_ABSOLUTE_TIMEOUT",
        "required": false,
        "default_value": "168h0m0s",
        "description": "Operator session absolute timeout."
      },
      {
        "name": "PRESSLUFT_SESSION_COOKIE_SECURE",
        "required": false,
        "description": "Override secure-cookie behavior."
      },
      {
        "name": "PRESSLUFT_BOOTSTRAP_ADMIN_EMAIL",
        "required": false,
        "description": "Bootstrap admin email for non-dev mode."
      },
      {
        "name": "PRESSLUFT_BOOTSTRAP_ADMIN_PASSWORD",
        "required": false,
        "description": "Bootstrap admin password for non-dev mode."
      },
      {
        "name": "PRESSLUFT_BOOTSTRAP_ADMIN_PASSWORD_FILE",
        "required": false,
        "description": "File-based bootstrap admin password source."
      },
      {
        "name": "PRESSLUFT_ANSIBLE_DIR",
        "required": false,
        "description": "Working directory used to resolve ansible paths."
      },
      {
        "name": "PRESSLUFT_ANSIBLE_BIN",
        "required": false,
        "description": "Path to ansible-playbook."
      }
    ]
  }
} as const

export type ExecutionMode = typeof platformContract.execution_modes[number]
export type SupportLevel = typeof platformContract.support_levels[number]
export type ServerStatus = typeof platformContract.server_statuses[number]
export type SetupState = typeof platformContract.setup_states[number]
export type NodeStatus = typeof platformContract.node_statuses[number]
export type CallbackURLMode = typeof platformContract.callback_url_modes[number]
export type JobStatus = typeof platformContract.job_statuses[number]
export type JobTerminalStatus = typeof platformContract.job_terminal_statuses[number]
export type JobKind = typeof platformContract.job_kinds[number]["kind"]
export type JobKindSpec = typeof platformContract.job_kinds[number]
export type WorkflowStep = typeof platformContract.job_kinds[number]["steps"][number]
export const jobKindLabels: Record<JobKind, string> = Object.fromEntries(
  platformContract.job_kinds.map((spec) => [spec.kind, spec.label]),
) as Record<JobKind, string>
export const jobKindSteps: Record<JobKind, readonly WorkflowStep[]> = Object.fromEntries(
  platformContract.job_kinds.map((spec) => [spec.kind, spec.steps]),
) as Record<JobKind, readonly WorkflowStep[]>
export const inProgressServerStatuses: readonly ServerStatus[] = platformContract.server_status_groups.in_progress
export const mutationBlockedServerStatuses: readonly ServerStatus[] = platformContract.server_status_groups.mutation_blocked
export const destructiveServerStatuses: readonly ServerStatus[] = platformContract.server_status_groups.destructive
export const reachableNodeStatuses: readonly NodeStatus[] = platformContract.reachable_node_statuses
export const jobTerminalStatuses: readonly JobTerminalStatus[] = platformContract.job_terminal_statuses
