package contract

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"slices"
	"sort"
	"strings"
	"time"

	"pressluft/internal/apitypes"
	"pressluft/internal/auth"
	"pressluft/internal/orchestrator"
	"pressluft/internal/platform"
)

var (
	timeType           = reflect.TypeFor[time.Time]()
	rawMessageType     = reflect.TypeFor[json.RawMessage]()
	serverStatusType   = reflect.TypeFor[platform.ServerStatus]()
	setupStateType     = reflect.TypeFor[platform.SetupState]()
	nodeStatusType     = reflect.TypeFor[platform.NodeStatus]()
	supportLevelType   = reflect.TypeFor[platform.SupportLevel]()
	callbackModeType   = reflect.TypeFor[platform.CallbackURLMode]()
	jobStatusType      = reflect.TypeFor[orchestrator.JobStatus]()
	jobKindType        = reflect.TypeFor[orchestrator.JobKind]()
	authCapabilityType = reflect.TypeFor[auth.Capability]()
	authRoleType       = reflect.TypeFor[auth.Role]()
)

type apiTypeRegistry struct {
	types       map[string]reflect.Type
	namesByType map[reflect.Type]string
}

func newAPITypeRegistry() apiTypeRegistry {
	names := make([]string, 0, len(apitypes.PublishedTypes))
	for name := range apitypes.PublishedTypes {
		names = append(names, name)
	}
	sort.Strings(names)

	registry := apiTypeRegistry{
		types:       make(map[string]reflect.Type, len(names)),
		namesByType: make(map[reflect.Type]string, len(names)),
	}
	for _, name := range names {
		typ := reflect.TypeOf(apitypes.PublishedTypes[name])
		registry.types[name] = typ
		registry.namesByType[typ] = name
	}
	return registry
}

func RenderAPITypeScriptModule() (string, error) {
	registry := newAPITypeRegistry()

	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/pressluft-contractgen; DO NOT EDIT.\n")
	out.WriteString("import type {\n")
	out.WriteString("  CallbackURLMode,\n")
	out.WriteString("  JobKind,\n")
	out.WriteString("  JobStatus,\n")
	out.WriteString("  NodeStatus,\n")
	out.WriteString("  ServerStatus,\n")
	out.WriteString("  SetupState,\n")
	out.WriteString("  SupportLevel,\n")
	out.WriteString("} from '~/lib/platform-contract.generated'\n\n")
	out.WriteString(fmt.Sprintf("export type Capability = %s\n", quotedUnion(capabilitiesToStrings(auth.AllCapabilities()))))
	out.WriteString("export type Role = 'admin'\n\n")

	names := make([]string, 0, len(registry.types))
	for name := range registry.types {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		typ := registry.types[name]
		rendered, err := renderExportedType(name, typ, registry)
		if err != nil {
			return "", err
		}
		out.WriteString(rendered)
		out.WriteString("\n")
	}

	return out.String(), nil
}

func renderExportedType(name string, typ reflect.Type, registry apiTypeRegistry) (string, error) {
	if typ.Kind() == reflect.Map {
		rendered, err := renderTSType(typ, registry)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("export type %s = %s\n", name, rendered), nil
	}
	if typ.Kind() != reflect.Struct {
		rendered, err := renderTSType(typ, registry)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("export type %s = %s\n", name, rendered), nil
	}

	var out bytes.Buffer
	out.WriteString(fmt.Sprintf("export interface %s {\n", name))
	for i := range typ.NumField() {
		field := typ.Field(i)
		if !field.IsExported() {
			continue
		}
		fieldName, optional, include := jsonFieldName(field)
		if !include {
			continue
		}
		rendered, err := renderTSType(field.Type, registry)
		if err != nil {
			return "", fmt.Errorf("%s.%s: %w", name, field.Name, err)
		}
		out.WriteString("  ")
		out.WriteString(fieldName)
		if optional {
			out.WriteString("?")
		}
		out.WriteString(": ")
		out.WriteString(rendered)
		out.WriteString("\n")
	}
	out.WriteString("}\n")
	return out.String(), nil
}

func renderTSType(typ reflect.Type, registry apiTypeRegistry) (string, error) {
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}

	switch {
	case typ == timeType:
		return "string", nil
	case typ == rawMessageType:
		return "unknown", nil
	case typ == serverStatusType:
		return "ServerStatus", nil
	case typ == setupStateType:
		return "SetupState", nil
	case typ == nodeStatusType:
		return "NodeStatus", nil
	case typ == supportLevelType:
		return "SupportLevel", nil
	case typ == callbackModeType:
		return "CallbackURLMode", nil
	case typ == jobStatusType:
		return "JobStatus", nil
	case typ == jobKindType:
		return "JobKind", nil
	case typ == authCapabilityType:
		return "Capability", nil
	case typ == authRoleType:
		return "Role", nil
	}

	if name, ok := registry.namesByType[typ]; ok {
		return name, nil
	}

	switch typ.Kind() {
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.String:
		return "string", nil
	case reflect.Slice, reflect.Array:
		valueType, err := renderTSType(typ.Elem(), registry)
		if err != nil {
			return "", err
		}
		return valueType + "[]", nil
	case reflect.Map:
		keyType, err := renderMapKeyType(typ.Key())
		if err != nil {
			return "", err
		}
		valueType, err := renderTSType(typ.Elem(), registry)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("Record<%s, %s>", keyType, valueType), nil
	case reflect.Struct:
		return renderInlineStructType(typ, registry)
	case reflect.Interface:
		return "unknown", nil
	default:
		return "", fmt.Errorf("unsupported type %s", typ.String())
	}
}

func renderInlineStructType(typ reflect.Type, registry apiTypeRegistry) (string, error) {
	fields := make([]string, 0, typ.NumField())
	for i := range typ.NumField() {
		field := typ.Field(i)
		if !field.IsExported() {
			continue
		}
		fieldName, optional, include := jsonFieldName(field)
		if !include {
			continue
		}
		rendered, err := renderTSType(field.Type, registry)
		if err != nil {
			return "", err
		}
		if optional {
			fields = append(fields, fmt.Sprintf("%s?: %s", fieldName, rendered))
			continue
		}
		fields = append(fields, fmt.Sprintf("%s: %s", fieldName, rendered))
	}
	return "{ " + strings.Join(fields, "; ") + " }", nil
}

func renderMapKeyType(typ reflect.Type) (string, error) {
	switch typ.Kind() {
	case reflect.String:
		return "string", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "number", nil
	default:
		return "", fmt.Errorf("unsupported map key type %s", typ.String())
	}
}

func jsonFieldName(field reflect.StructField) (name string, optional bool, include bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false, false
	}
	if tag == "" {
		return field.Name, false, true
	}
	parts := strings.Split(tag, ",")
	name = parts[0]
	if name == "" {
		name = field.Name
	}
	optional = slices.Contains(parts[1:], "omitempty")
	return name, optional, true
}

func capabilitiesToStrings(values []auth.Capability) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, string(value))
	}
	sort.Strings(out)
	return out
}

func quotedUnion(values []string) string {
	if len(values) == 0 {
		return "never"
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, " | ")
}
