// Package contract exposes the runtime contract in machine-readable forms.
package contract

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"time"

	"pressluft/internal/envconfig"
	"pressluft/internal/orchestrator"
	"pressluft/internal/platform"
)

type Spec struct {
	ExecutionModes      []string               `json:"execution_modes"`
	SupportLevels       []string               `json:"support_levels"`
	ServerStatuses      []string               `json:"server_statuses"`
	ServerStatusGroups  ServerStatusGroups     `json:"server_status_groups"`
	SetupStates         []string               `json:"setup_states"`
	NodeStatuses        []string               `json:"node_statuses"`
	ReachableNodeStatus []string               `json:"reachable_node_statuses"`
	NodeThresholds      NodeThresholds         `json:"node_thresholds"`
	CallbackURLModes    []string               `json:"callback_url_modes"`
	JobStatuses         []string               `json:"job_statuses"`
	JobTerminalStatuses []string               `json:"job_terminal_statuses"`
	JobKinds            []JobKindSpec          `json:"job_kinds"`
	ConfigScopes        map[string][]EnvVarDoc `json:"config_scopes"`
}

type ServerStatusGroups struct {
	InProgress      []string `json:"in_progress"`
	MutationBlocked []string `json:"mutation_blocked"`
	Destructive     []string `json:"destructive"`
}

type NodeThresholds struct {
	UnhealthySeconds int `json:"unhealthy_seconds"`
	OfflineSeconds   int `json:"offline_seconds"`
}

type JobKindSpec struct {
	Kind            string         `json:"kind"`
	Label           string         `json:"label"`
	AllowedStatuses []string       `json:"allowed_statuses"`
	Destructive     bool           `json:"destructive"`
	Experimental    bool           `json:"experimental"`
	ExecutionPath   string         `json:"execution_path"`
	DispatchPolicy  DispatchPolicy `json:"dispatch_policy"`
	TimeoutSeconds  int64          `json:"timeout_seconds"`
	RetryLimit      int            `json:"retry_limit"`
	Recovery        string         `json:"recovery"`
	QueuedStatus    string         `json:"queued_server_status,omitempty"`
	Steps           []Step         `json:"steps"`
}

type DispatchPolicy struct {
	QueueServer bool `json:"queue_server"`
}

type Step struct {
	Key   string `json:"key"`
	Label string `json:"label"`
}

type EnvVarDoc struct {
	Name         string `json:"name"`
	Required     bool   `json:"required"`
	DefaultValue string `json:"default_value,omitempty"`
	Description  string `json:"description"`
}

func SpecData() Spec {
	configScopes := map[string][]EnvVarDoc{
		"control-plane": toEnvDocs(envconfig.ControlPlaneEnvSpec()),
		"agent":         toEnvDocs(envconfig.AgentEnvSpec()),
	}

	return Spec{
		ExecutionModes:      toStrings(platform.AllExecutionModes()),
		SupportLevels:       toStrings(platform.AllSupportLevels()),
		ServerStatuses:      toStrings(platform.AllServerStatuses()),
		ServerStatusGroups:  ServerStatusGroups{InProgress: toStrings(platform.InProgressServerStatuses()), MutationBlocked: toStrings(platform.MutationBlockedServerStatuses()), Destructive: toStrings(platform.DestructiveActionServerStatuses())},
		SetupStates:         toStrings(platform.AllSetupStates()),
		NodeStatuses:        toStrings(platform.AllNodeStatuses()),
		ReachableNodeStatus: toStrings(platform.ReachableNodeStatuses()),
		NodeThresholds:      NodeThresholds{UnhealthySeconds: platform.NodeUnhealthyThresholdSeconds, OfflineSeconds: platform.NodeOfflineThresholdSeconds},
		CallbackURLModes:    toStrings(platform.AllCallbackURLModes()),
		JobStatuses: []string{
			string(orchestrator.JobStatusQueued),
			string(orchestrator.JobStatusRunning),
			string(orchestrator.JobStatusSucceeded),
			string(orchestrator.JobStatusFailed),
		},
		JobTerminalStatuses: []string{
			string(orchestrator.JobStatusSucceeded),
			string(orchestrator.JobStatusFailed),
		},
		JobKinds:     jobKindSpecs(),
		ConfigScopes: configScopes,
	}
}

func JSON() ([]byte, error) {
	return json.MarshalIndent(SpecData(), "", "  ")
}

func RenderTypeScriptModule() (string, error) {
	payload, err := json.MarshalIndent(SpecData(), "", "  ")
	if err != nil {
		return "", fmt.Errorf("marshal contract: %w", err)
	}

	var out bytes.Buffer
	out.WriteString("// Code generated by cmd/pressluft-contractgen; DO NOT EDIT.\n")
	out.WriteString("export const platformContract = ")
	out.Write(payload)
	out.WriteString(" as const\n\n")
	out.WriteString("export type ExecutionMode = typeof platformContract.execution_modes[number]\n")
	out.WriteString("export type SupportLevel = typeof platformContract.support_levels[number]\n")
	out.WriteString("export type ServerStatus = typeof platformContract.server_statuses[number]\n")
	out.WriteString("export type SetupState = typeof platformContract.setup_states[number]\n")
	out.WriteString("export type NodeStatus = typeof platformContract.node_statuses[number]\n")
	out.WriteString("export type CallbackURLMode = typeof platformContract.callback_url_modes[number]\n")
	out.WriteString("export type JobStatus = typeof platformContract.job_statuses[number]\n")
	out.WriteString("export type JobTerminalStatus = typeof platformContract.job_terminal_statuses[number]\n")
	out.WriteString("export type JobKind = typeof platformContract.job_kinds[number][\"kind\"]\n")
	out.WriteString("export type JobKindSpec = typeof platformContract.job_kinds[number]\n")
	out.WriteString("export type WorkflowStep = typeof platformContract.job_kinds[number][\"steps\"][number]\n")
	out.WriteString("export const jobKindLabels: Record<JobKind, string> = Object.fromEntries(\n")
	out.WriteString("  platformContract.job_kinds.map((spec) => [spec.kind, spec.label]),\n")
	out.WriteString(") as Record<JobKind, string>\n")
	out.WriteString("export const jobKindSteps: Record<JobKind, readonly WorkflowStep[]> = Object.fromEntries(\n")
	out.WriteString("  platformContract.job_kinds.map((spec) => [spec.kind, spec.steps]),\n")
	out.WriteString(") as Record<JobKind, readonly WorkflowStep[]>\n")
	out.WriteString("export const inProgressServerStatuses: readonly ServerStatus[] = platformContract.server_status_groups.in_progress\n")
	out.WriteString("export const mutationBlockedServerStatuses: readonly ServerStatus[] = platformContract.server_status_groups.mutation_blocked\n")
	out.WriteString("export const destructiveServerStatuses: readonly ServerStatus[] = platformContract.server_status_groups.destructive\n")
	out.WriteString("export const reachableNodeStatuses: readonly NodeStatus[] = platformContract.reachable_node_statuses\n")
	out.WriteString("export const jobTerminalStatuses: readonly JobTerminalStatus[] = platformContract.job_terminal_statuses\n")
	return out.String(), nil
}

func jobKindSpecs() []JobKindSpec {
	specs := orchestrator.SupportedJobKinds()
	out := make([]JobKindSpec, 0, len(specs))
	for _, spec := range specs {
		out = append(out, JobKindSpec{
			Kind:            string(spec.Kind),
			Label:           spec.Label,
			AllowedStatuses: toStrings(spec.AllowedStatuses),
			Destructive:     spec.Destructive,
			Experimental:    spec.Experimental,
			ExecutionPath:   spec.ExecutionPath,
			DispatchPolicy:  DispatchPolicy{QueueServer: spec.DispatchPolicy.QueueServer},
			TimeoutSeconds:  int64(spec.Timeout / time.Second),
			RetryLimit:      spec.RetryLimit,
			Recovery:        spec.Recovery,
			QueuedStatus:    string(spec.QueuedStatus),
			Steps:           toSteps(spec.Steps),
		})
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Kind < out[j].Kind
	})
	return out
}

func toSteps(steps []orchestrator.WorkflowStep) []Step {
	out := make([]Step, 0, len(steps))
	for _, step := range steps {
		out = append(out, Step{Key: step.Key, Label: step.Label})
	}
	return out
}

func toEnvDocs(specs []envconfig.EnvVarSpec) []EnvVarDoc {
	out := make([]EnvVarDoc, 0, len(specs))
	for _, spec := range specs {
		out = append(out, EnvVarDoc{
			Name:         spec.Name,
			Required:     spec.Required,
			DefaultValue: spec.DefaultValue,
			Description:  spec.Description,
		})
	}
	return out
}

func toStrings[T ~string](values []T) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, string(value))
	}
	return out
}
